package com.example.csvreader.data

import java.net.HttpURLConnection
import java.net.URL
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** Shared configuration for the Nilai KPI feed. */
object KpiConfig {
    const val STATION_CODE = "C4-NIL-5-85"
    const val SHEET_CSV_URL =
        "https://docs.google.com/spreadsheets/d/1-crbMCbGgsHydSUQzhVpWHwS7wRniHt8TN9z-7XQ8Pk/gviz/tq?tqx=out:csv&gid=0"
}

data class KpiMetric(
    val name: String,
    val targetPercent: Double,
    val currentPercent: Double?,
    val leftToTarget: Int,
    val total: Int,
)

data class KpiSnapshot(
    val stationCode: String,
    val stationName: String,
    val zone: String,
    val sourceUpdatedAt: String,
    val fetchedAt: LocalDateTime,
    val metrics: List<KpiMetric>,
)

class KpiRepository {
    suspend fun fetchStationKpis(): KpiSnapshot = withContext(Dispatchers.IO) {
        val connection =
            (URL("${KpiConfig.SHEET_CSV_URL}&cacheBust=${System.currentTimeMillis()}")
                    .openConnection() as HttpURLConnection)
                .apply {
                    connectTimeout = 15_000
                    readTimeout = 20_000
                    requestMethod = "GET"
                }

        try {
            if (connection.responseCode !in 200..299) {
                error("KPI sheet returned HTTP ${connection.responseCode}")
            }
            KpiCsvParser.parse(
                csv = connection.inputStream.bufferedReader().use { it.readText() },
                stationCode = KpiConfig.STATION_CODE,
            )
        } finally {
            connection.disconnect()
        }
    }
}

/**
 * Parses RFC-4180-style CSV, including the multi-line headings generated by Google Sheets.
 * Column positions mirror the master KPI sheet's three metric groups.
 */
object KpiCsvParser {
    fun parse(csv: String, stationCode: String): KpiSnapshot {
        val records = parseRecords(csv)
        require(records.size >= 2) { "The KPI sheet is empty" }

        val header = records.first()
        val station =
            records.drop(1).firstOrNull { row -> row.getOrNull(1)?.trim() == stationCode }
                ?: error("Station $stationCode was not found in the KPI sheet")

        fun metric(
            name: String,
            target: Double,
            totalColumn: Int,
            currentColumn: Int,
            gapColumn: Int,
        ) =
            KpiMetric(
                name = name,
                targetPercent = target,
                currentPercent = station.getOrNull(currentColumn).toPercentOrNull(),
                leftToTarget = station.getOrNull(gapColumn).toIntOrZero(),
                total = station.getOrNull(totalColumn).toIntOrZero(),
            )

        return KpiSnapshot(
            stationCode = stationCode,
            stationName = station.getOrNull(3).orEmpty().ifBlank { "Nilai" },
            zone = station.getOrNull(0).orEmpty(),
            sourceUpdatedAt = header.getOrNull(1).orEmpty().substringBefore(" GROUP").trim(),
            fetchedAt = LocalDateTime.now(),
            metrics =
                listOf(
                    metric("FIFO D0", 95.0, 4, 5, 6),
                    metric("PRIOR D0", 92.0, 9, 10, 11),
                    metric("D0 Completion", 88.0, 14, 15, 16),
                ),
        )
    }

    private fun parseRecords(csv: String): List<List<String>> {
        val records = mutableListOf<List<String>>()
        var record = mutableListOf<String>()
        val field = StringBuilder()
        var quoted = false
        var index = 0

        while (index < csv.length) {
            val character = csv[index]
            when {
                character == '"' && quoted && csv.getOrNull(index + 1) == '"' -> {
                    field.append('"')
                    index++
                }
                character == '"' -> quoted = !quoted
                character == ',' && !quoted -> {
                    record.add(field.toString())
                    field.clear()
                }
                (character == '\n' || character == '\r') && !quoted -> {
                    if (character == '\r' && csv.getOrNull(index + 1) == '\n') index++
                    record.add(field.toString())
                    field.clear()
                    if (record.any { it.isNotEmpty() }) records.add(record)
                    record = mutableListOf()
                }
                else -> field.append(character)
            }
            index++
        }

        if (field.isNotEmpty() || record.isNotEmpty()) {
            record.add(field.toString())
            records.add(record)
        }
        return records
    }

    private fun String?.toPercentOrNull(): Double? =
        this?.trim()?.removeSuffix("%")?.takeIf { it.isNotEmpty() }?.toDoubleOrNull()

    private fun String?.toIntOrZero(): Int =
        this?.trim()?.replace(",", "")?.toDoubleOrNull()?.toInt() ?: 0
}

fun KpiSnapshot.fetchedAtLabel(): String =
    fetchedAt.format(DateTimeFormatter.ofPattern("dd MMM, h:mm a"))
