package com.example.csvreader.data

import java.net.HttpURLConnection
import java.net.URL
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** Shared configuration for the Nilai KPI feed. */
object KpiConfig {
    const val STATION_CODE = "C4-NIL-5-85"
    const val SHEET_CSV_URL =
        "https://docs.google.com/spreadsheets/d/1-crbMCbGgsHydSUQzhVpWHwS7wRniHt8TN9z-7XQ8Pk/gviz/tq?tqx=out:csv&gid=0"
    const val RAW_DATA_CSV_URL =
        "https://docs.google.com/spreadsheets/d/1-crbMCbGgsHydSUQzhVpWHwS7wRniHt8TN9z-7XQ8Pk/gviz/tq?tqx=out:csv&gid=1615722066"
}

data class KpiMetric(
    val name: String,
    val targetPercent: Double,
    val currentPercent: Double?,
    val leftToTarget: Int,
    val total: Int,
)

data class KpiSnapshot(
    val stationCode: String,
    val stationName: String,
    val zone: String,
    val sourceUpdatedAt: String,
    val fetchedAtMillis: Long,
    val metrics: List<KpiMetric>,
)

data class StatusCount(val status: String, val count: Int)

data class MetricBreakdown(
    val metricName: String,
    val title: String,
    val totalPending: Int,
    val statuses: List<StatusCount>,
    val note: String,
    val sourceUpdatedAt: String = "",
)

class KpiRepository {
    suspend fun fetchStationKpis(): KpiSnapshot = withContext(Dispatchers.IO) {
        val connection =
            (URL("${KpiConfig.SHEET_CSV_URL}&cacheBust=${System.currentTimeMillis()}")
                    .openConnection() as HttpURLConnection)
                .apply {
                    connectTimeout = 15_000
                    readTimeout = 20_000
                    requestMethod = "GET"
                }

        try {
            if (connection.responseCode !in 200..299) {
                error("KPI sheet returned HTTP ${connection.responseCode}")
            }
            KpiCsvParser.parse(
                csv = connection.inputStream.bufferedReader().use { it.readText() },
                stationCode = KpiConfig.STATION_CODE,
            )
        } finally {
            connection.disconnect()
        }
    }

    suspend fun fetchMetricBreakdown(metricName: String): MetricBreakdown =
        withContext(Dispatchers.IO) {
            if (metricName == "D0 Completion") {
                return@withContext MetricBreakdown(
                    metricName = metricName,
                    title = "D0 Completion leftover",
                    totalPending = 0,
                    statuses = emptyList(),
                    note =
                        "The Raw Data tab only pivots FIFO and PRIOR leftovers. Completion tracking IDs are not in this published structure.",
                )
            }

            val connection =
                (URL("${KpiConfig.RAW_DATA_CSV_URL}&cacheBust=${System.currentTimeMillis()}")
                        .openConnection() as HttpURLConnection)
                    .apply {
                        connectTimeout = 15_000
                        readTimeout = 20_000
                        requestMethod = "GET"
                    }
            try {
                if (connection.responseCode !in 200..299) {
                    error("Raw Data tab returned HTTP ${connection.responseCode}")
                }
                KpiCsvParser.parseRawData(
                    csv = connection.inputStream.bufferedReader().use { it.readText() },
                    stationCode = KpiConfig.STATION_CODE,
                    metricName = metricName,
                )
            } finally {
                connection.disconnect()
            }
        }
}

/**
 * Parses RFC-4180-style CSV, including the multi-line headings generated by Google Sheets.
 * Column positions mirror the master KPI sheet's three metric groups.
 */
object KpiCsvParser {
    fun parse(csv: String, stationCode: String): KpiSnapshot {
        val records = parseRecords(csv)
        require(records.size >= 2) { "The KPI sheet is empty" }

        val header = records.first()
        val station =
            records.drop(1).firstOrNull { row -> row.getOrNull(1)?.trim() == stationCode }
                ?: error("Station $stationCode was not found in the KPI sheet")

        fun metric(
            name: String,
            target: Double,
            totalColumn: Int,
            currentColumn: Int,
            gapColumn: Int,
        ) =
            KpiMetric(
                name = name,
                targetPercent = target,
                currentPercent = station.getOrNull(currentColumn).toPercentOrNull(),
                leftToTarget = station.getOrNull(gapColumn).toIntOrZero(),
                total = station.getOrNull(totalColumn).toIntOrZero(),
            )

        return KpiSnapshot(
            stationCode = stationCode,
            stationName = station.getOrNull(3).orEmpty().ifBlank { "Nilai" },
            zone = station.getOrNull(0).orEmpty(),
            sourceUpdatedAt = header.getOrNull(1).orEmpty().substringBefore(" GROUP").trim(),
            fetchedAtMillis = System.currentTimeMillis(),
            metrics =
                listOf(
                    metric("FIFO D0", 95.0, 4, 5, 6),
                    metric("PRIOR D0", 92.0, 9, 10, 11),
                    metric("D0 Completion", 88.0, 14, 15, 16),
                ),
        )
    }

    fun parseRawData(csv: String, stationCode: String, metricName: String): MetricBreakdown {
        val records = parseRecords(csv)
        require(records.isNotEmpty()) { "The Raw Data tab is empty" }

        val header = records.first()
        val sourceUpdatedAt =
            Regex("""\d{2}/\d{2}/\d{4}\s+\d{1,2}:\d{2}:\d{2}\s+[AP]M""")
                .find(header.getOrNull(1).orEmpty())
                ?.value
                .orEmpty()
        val station =
            records.firstOrNull { row -> row.any { cell -> cell.trim() == stationCode } }
                ?: error("Station $stationCode was not found in Raw Data")

        val stationCols =
            station.mapIndexedNotNull { index, cell ->
                index.takeIf { cell.trim() == stationCode }
            }
        val fifoCol = stationCols.getOrNull(0) ?: 1
        val priorCol = stationCols.getOrNull(1) ?: stationCols.getOrNull(0) ?: 8
        val fifo = extractStatusBlock(station, header, fifoCol)
        val prior = extractStatusBlock(station, header, priorCol)
        val note =
            "This tab counts tracking_id by status. It does not list tracking numbers. Import the parcel dump in columns A-L to show successful and pending tracking IDs."

        return if (metricName.startsWith("PRIOR")) {
            MetricBreakdown(
                metricName = metricName,
                title = "PRIOR D0 left to success",
                totalPending = prior.totalPending,
                statuses = prior.statuses,
                note = note,
                sourceUpdatedAt = sourceUpdatedAt,
            )
        } else {
            MetricBreakdown(
                metricName = metricName,
                title = "FIFO D0 left to attempt",
                totalPending = fifo.totalPending,
                statuses = fifo.statuses,
                note = note,
                sourceUpdatedAt = sourceUpdatedAt,
            )
        }
    }

    private data class StatusBlock(val statuses: List<StatusCount>, val totalPending: Int)

    private fun extractStatusBlock(
        row: List<String>,
        header: List<String>,
        stationCol: Int,
    ): StatusBlock {
        val statuses = mutableListOf<StatusCount>()
        var totalPending = 0
        val last = maxOf(row.size, header.size)
        for (index in (stationCol + 1) until last) {
            val cell = row.getOrNull(index).orEmpty()
            if (cell.trim().looksLikeStation()) break
            val label = header.getOrNull(index).toHeaderLabel()
            if (label == "Grand Total") {
                totalPending = cell.toIntOrZero()
                break
            }
            if (label in STATUS_LABELS.values) {
                statuses += StatusCount(label, cell.toIntOrZero())
            }
        }
        val pending = statuses.filter { it.count > 0 }
        return StatusBlock(
            statuses = pending,
            totalPending = if (totalPending > 0) totalPending else pending.sumOf { it.count },
        )
    }

    private fun parseRecords(csv: String): List<List<String>> {
        val records = mutableListOf<List<String>>()
        var record = mutableListOf<String>()
        val field = StringBuilder()
        var quoted = false
        var index = 0

        while (index < csv.length) {
            val character = csv[index]
            when {
                character == '"' && quoted && csv.getOrNull(index + 1) == '"' -> {
                    field.append('"')
                    index++
                }
                character == '"' -> quoted = !quoted
                character == ',' && !quoted -> {
                    record.add(field.toString())
                    field.clear()
                }
                (character == '\n' || character == '\r') && !quoted -> {
                    if (character == '\r' && csv.getOrNull(index + 1) == '\n') index++
                    record.add(field.toString())
                    field.clear()
                    if (record.any { it.isNotEmpty() }) records.add(record)
                    record = mutableListOf()
                }
                else -> field.append(character)
            }
            index++
        }

        if (field.isNotEmpty() || record.isNotEmpty()) {
            record.add(field.toString())
            records.add(record)
        }
        return records
    }

    private fun String?.toPercentOrNull(): Double? =
        this?.trim()?.removeSuffix("%")?.takeIf { it.isNotEmpty() }?.toDoubleOrNull()

    private fun String?.toIntOrZero(): Int =
        this?.trim()?.replace(",", "")?.toDoubleOrNull()?.toInt() ?: 0

    private fun String.looksLikeStation(): Boolean =
        Regex("""^C\d-[A-Z0-9]+-\d+-\d+$""", RegexOption.IGNORE_CASE).matches(trim())

    private fun String?.toHeaderLabel(): String {
        val raw =
            this.orEmpty()
                .replace("🎉", "")
                .replace(Regex("SUCCESS", RegexOption.IGNORE_CASE), "")
                .replace(Regex("granular_status", RegexOption.IGNORE_CASE), "")
                .replace(Regex("Data Status", RegexOption.IGNORE_CASE), "")
                .replace(Regex("\\s+"), " ")
                .trim()
        if (raw.contains("Grand Total", ignoreCase = true)) return "Grand Total"
        return STATUS_LABELS[raw.lowercase()] ?: raw
    }

    private val STATUS_LABELS =
        mapOf(
            "arrived at sorting hub" to "Arrived at Sorting Hub",
            "cancelled" to "Cancelled",
            "en-route to sorting hub" to "En-route to Sorting Hub",
            "on hold" to "On Hold",
            "on vehicle for delivery" to "On Vehicle for Delivery",
            "pending reschedule" to "Pending Reschedule",
        )
}

fun KpiSnapshot.fetchedAtLabel(): String =
    SimpleDateFormat("dd MMM, h:mm a", Locale.getDefault()).format(Date(fetchedAtMillis))
